name: Auto Build Electron

on:
  push:
    tags:
      - v*
jobs:
  build-electron-job:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-15, windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'
        
      - name: install deps
        run: yarn --frozen-lockfile
      
      - name: build electron
        run: yarn build
